name: Migrate up

on: workflow_dispatch

jobs:
  migrate-up:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.GCP_ARTIFACT_REGISTRY }}/migrate:latest -f ./Dockerfile.migrate .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY }}/migrate:latest

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Run migration
        run: gcloud run jobs execute task-management-migrate --project awell-sandbox --region us-central1
