name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.GCP_ARTIFACT_REGISTRY }}/backend:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY }}/backend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_CLOUD_RUN_SERVICE }} \
          --image ${{ secrets.GCP_ARTIFACT_REGISTRY }}/backend:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars DATABASE_URL="postgresql://${{ secrets.DATABASE_USER }}:${{ secrets.DATABASE_PASSWORD }}@${{ secrets.DATABASE_NAME}}?host=/cloudsql/${{ secrets.GCP_SQL_INSTANCE_CONNECTION_NAME }}" \
          --port 8080

# GCP_PROJECT_ID: Your Google Cloud project ID
# GCP_SA_KEY: Your Google Cloud service account key
# GCP_ARTIFACT_REGISTRY: Your Google Cloud Artifact Registry
# GCP_CLOUD_RUN_SERVICE: Your Google Cloud Run service name
# DATABASE_USER: Your PostgreSQL database user
# DATABASE_PASSWORD: Your PostgreSQL database password
# DATABASE_NAME: Your PostgreSQL database name
# GCP_SQL_INSTANCE_CONNECTION_NAME: Your Google Cloud SQL instance connection name
